name: test-pi-bt
base: core18
version: '0.1'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict

apps:
  btattach:
    command: bin/btach
    daemon: oneshot
    plugs: [ bluetooth-control, serial-port ]

parts:
  launch:
    plugin: dump
    source: launch
  bluez:
    plugin: autotools
    source: https://git.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/bluez
    source-type: git
    source-branch: bluez/5.47
    configflags:
      - --prefix=/usr
      - --libexec=/usr/lib/
      - --enable-experimental
      - --enable-threads
      - --disable-cups
      - --enable-obex
      - --disable-systemd
      - --disable-silent-rules
      - --enable-test
      - --enable-deprecated
      - --enable-mesh
    build-packages:
      - libglib2.0-dev
      - libdbus-1-dev
      - libical-dev
      - libreadline6-dev
      - libudev-dev
      - udev
      - pkg-config
      - libjson-c-dev
    #stage-packages:
    #  - libical1a
    filesets:
      libical1a:
        - usr/lib/*/libical*
    stage:
      - usr/bin/btattach
      - -usr/lib/ddbluetooth/bluetoothd
      - -usr/lib/bluetooth/obexd
      - -usr/bin/bluetoothctl
      - -usr/bin/obexctl
      - -usr/bin/hciconfig
      - -usr/bin/hcidump
      - -usr/bin/hciattach
      - -usr/bin/hcitool
      - -usr/bin/sdptool
      - -usr/bin/btmon
      - -usr/bin/btmgmt
      - -usr/bin/meshctl
      - -usr/share/doc/libical1a/copyright
      #- $libical1a
